\i sql/encounterForm.sql;
\i sql/individualRegistrationForm.sql;
\i sql/programEnrolmentForms.sql;
\i sql/programExitForms.sql;
SELECT setupEncounterForm();
SELECT setupIndividualRegistrationForm();
SELECT setupProgramEnrolmentForms();
SELECT setupProgramExitForms();
\i sql/villages.sql;